const SERVICE_SETTINGS = Object.freeze({
  separationCriteria: ',',
  minNumberOfCoaches: 2,
  maxNumberOfCoaches: 5,
  minLengthOfCoachesName: 2,
  maxLengthOfCoachesName: 4,
  maxNumberOfMenus: 2,
  error: '[ERROR]',
});

const MENUS_FOR_EACH_CATEGORIES = {
  일식: {
    1: '규동',
    2: '우동',
    3: '미소시루',
    4: '스시',
    5: '가츠동',
    6: '오니기리',
    7: '하이라이스',
    8: '라멘',
    9: '오코노미야끼',
  },
  한식: {
    1: '김밥',
    2: '김치찌개',
    3: '쌈밥',
    4: '된장찌개',
    5: '비빔밥',
    6: '칼국수',
    7: '불고기',
    8: '떡볶이',
    9: '제육볶음',
  },
  중식: {
    1: '깐풍기',
    2: '볶음면',
    3: '동파육',
    4: '짜장면',
    5: '짬뽕',
    6: '마파두부',
    7: '탕수육',
    8: '토마토 달걀볶음',
    9: '고추잡채',
  },
  아시안: {
    1: '팟타이',
    2: '카오 팟',
    3: '나시고렝',
    4: '파인애플 볶음밥',
    5: '쌀국수',
    6: '똠얌꿍',
    7: '반미',
    8: '월남쌈',
    9: '분짜',
  },
  양식: {
    1: '라자냐',
    2: '그라탱',
    3: '뇨끼',
    4: '끼슈',
    5: '프렌치 토스트',
    6: '바게트',
    7: '스파게티',
    8: '피자',
    9: '파니니',
  },
};

module.exports = { SERVICE_SETTINGS, MENUS_FOR_EACH_CATEGORIES };
